/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/merkle_patricia_trie.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/merkle_patricia_trie.pb-c.h"
void   merkle_patricia_trie__mptnode__init
                     (MerklePatriciaTrie__MPTNode         *message)
{
  static const MerklePatriciaTrie__MPTNode init_value = MERKLE_PATRICIA_TRIE__MPTNODE__INIT;
  *message = init_value;
}
size_t merkle_patricia_trie__mptnode__get_packed_size
                     (const MerklePatriciaTrie__MPTNode *message)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptnode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t merkle_patricia_trie__mptnode__pack
                     (const MerklePatriciaTrie__MPTNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptnode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t merkle_patricia_trie__mptnode__pack_to_buffer
                     (const MerklePatriciaTrie__MPTNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptnode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MerklePatriciaTrie__MPTNode *
       merkle_patricia_trie__mptnode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MerklePatriciaTrie__MPTNode *)
     protobuf_c_message_unpack (&merkle_patricia_trie__mptnode__descriptor,
                                allocator, len, data);
}
void   merkle_patricia_trie__mptnode__free_unpacked
                     (MerklePatriciaTrie__MPTNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &merkle_patricia_trie__mptnode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   merkle_patricia_trie__mptfull_node__init
                     (MerklePatriciaTrie__MPTFullNode         *message)
{
  static const MerklePatriciaTrie__MPTFullNode init_value = MERKLE_PATRICIA_TRIE__MPTFULL_NODE__INIT;
  *message = init_value;
}
size_t merkle_patricia_trie__mptfull_node__get_packed_size
                     (const MerklePatriciaTrie__MPTFullNode *message)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptfull_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t merkle_patricia_trie__mptfull_node__pack
                     (const MerklePatriciaTrie__MPTFullNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptfull_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t merkle_patricia_trie__mptfull_node__pack_to_buffer
                     (const MerklePatriciaTrie__MPTFullNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptfull_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MerklePatriciaTrie__MPTFullNode *
       merkle_patricia_trie__mptfull_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MerklePatriciaTrie__MPTFullNode *)
     protobuf_c_message_unpack (&merkle_patricia_trie__mptfull_node__descriptor,
                                allocator, len, data);
}
void   merkle_patricia_trie__mptfull_node__free_unpacked
                     (MerklePatriciaTrie__MPTFullNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &merkle_patricia_trie__mptfull_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   merkle_patricia_trie__mptshort_node__init
                     (MerklePatriciaTrie__MPTShortNode         *message)
{
  static const MerklePatriciaTrie__MPTShortNode init_value = MERKLE_PATRICIA_TRIE__MPTSHORT_NODE__INIT;
  *message = init_value;
}
size_t merkle_patricia_trie__mptshort_node__get_packed_size
                     (const MerklePatriciaTrie__MPTShortNode *message)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptshort_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t merkle_patricia_trie__mptshort_node__pack
                     (const MerklePatriciaTrie__MPTShortNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptshort_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t merkle_patricia_trie__mptshort_node__pack_to_buffer
                     (const MerklePatriciaTrie__MPTShortNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &merkle_patricia_trie__mptshort_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MerklePatriciaTrie__MPTShortNode *
       merkle_patricia_trie__mptshort_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MerklePatriciaTrie__MPTShortNode *)
     protobuf_c_message_unpack (&merkle_patricia_trie__mptshort_node__descriptor,
                                allocator, len, data);
}
void   merkle_patricia_trie__mptshort_node__free_unpacked
                     (MerklePatriciaTrie__MPTShortNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &merkle_patricia_trie__mptshort_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor merkle_patricia_trie__mptnode__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MerklePatriciaTrie__MPTNode, type),
    &merkle_patricia_trie__mptnode__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MerklePatriciaTrie__MPTNode, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned merkle_patricia_trie__mptnode__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange merkle_patricia_trie__mptnode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor merkle_patricia_trie__mptnode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "merkle_patricia_trie.MPTNode",
  "MPTNode",
  "MerklePatriciaTrie__MPTNode",
  "merkle_patricia_trie",
  sizeof(MerklePatriciaTrie__MPTNode),
  2,
  merkle_patricia_trie__mptnode__field_descriptors,
  merkle_patricia_trie__mptnode__field_indices_by_name,
  1,  merkle_patricia_trie__mptnode__number_ranges,
  (ProtobufCMessageInit) merkle_patricia_trie__mptnode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor merkle_patricia_trie__mptfull_node__field_descriptors[2] =
{
  {
    "nodes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(MerklePatriciaTrie__MPTFullNode, n_nodes),
    offsetof(MerklePatriciaTrie__MPTFullNode, nodes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MerklePatriciaTrie__MPTFullNode, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned merkle_patricia_trie__mptfull_node__field_indices_by_name[] = {
  0,   /* field[0] = nodes */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange merkle_patricia_trie__mptfull_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor merkle_patricia_trie__mptfull_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "merkle_patricia_trie.MPTFullNode",
  "MPTFullNode",
  "MerklePatriciaTrie__MPTFullNode",
  "merkle_patricia_trie",
  sizeof(MerklePatriciaTrie__MPTFullNode),
  2,
  merkle_patricia_trie__mptfull_node__field_descriptors,
  merkle_patricia_trie__mptfull_node__field_indices_by_name,
  1,  merkle_patricia_trie__mptfull_node__number_ranges,
  (ProtobufCMessageInit) merkle_patricia_trie__mptfull_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor merkle_patricia_trie__mptshort_node__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MerklePatriciaTrie__MPTShortNode, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MerklePatriciaTrie__MPTShortNode, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned merkle_patricia_trie__mptshort_node__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange merkle_patricia_trie__mptshort_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor merkle_patricia_trie__mptshort_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "merkle_patricia_trie.MPTShortNode",
  "MPTShortNode",
  "MerklePatriciaTrie__MPTShortNode",
  "merkle_patricia_trie",
  sizeof(MerklePatriciaTrie__MPTShortNode),
  2,
  merkle_patricia_trie__mptshort_node__field_descriptors,
  merkle_patricia_trie__mptshort_node__field_indices_by_name,
  1,  merkle_patricia_trie__mptshort_node__number_ranges,
  (ProtobufCMessageInit) merkle_patricia_trie__mptshort_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue merkle_patricia_trie__mptnode__type__enum_values_by_number[3] =
{
  { "FULL", "MERKLE_PATRICIA_TRIE__MPTNODE__TYPE__FULL", 0 },
  { "SHORT", "MERKLE_PATRICIA_TRIE__MPTNODE__TYPE__SHORT", 1 },
  { "VALUE", "MERKLE_PATRICIA_TRIE__MPTNODE__TYPE__VALUE", 2 },
};
static const ProtobufCIntRange merkle_patricia_trie__mptnode__type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex merkle_patricia_trie__mptnode__type__enum_values_by_name[3] =
{
  { "FULL", 0 },
  { "SHORT", 1 },
  { "VALUE", 2 },
};
const ProtobufCEnumDescriptor merkle_patricia_trie__mptnode__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "merkle_patricia_trie.MPTNODE_TYPE",
  "MPTNODE_TYPE",
  "MerklePatriciaTrie__MPTNODETYPE",
  "merkle_patricia_trie",
  3,
  merkle_patricia_trie__mptnode__type__enum_values_by_number,
  3,
  merkle_patricia_trie__mptnode__type__enum_values_by_name,
  1,
  merkle_patricia_trie__mptnode__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
